# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#theme: jekyll-theme-so-simple
remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Joe Hoover"
description: "Postdoctoral Fellow<br>Management and Organizations<br>Northwestern University"
#baseurl: # the subpath of your site, e.g. "/blog"
url: "http://joe-hoover.com"
#markdown: kramdown
logo: "/images/mym_square.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  

google_analytics: UA-89081546-1

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: Joe Hoover
  picture: bih_map-1.png
  email: joseph.hoover@kellogg.northwestern.edu
  twitter: JoeEHoover
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Email
    url: mailto:joseph.hoover@kellogg.northwestern.edu
    icon: fas fa-envelope-square
  - title: linkedin 
    url: https:/linkedin/in/JoeEHoover
    icon: fab fa-linkedin-in
  - title: twitter
    url: https://twitter.com/JoeEHoover
    icon: fab fa-twitter-square
